apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api-server
          image: ghcr.io/sanchit36/api-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
